services:
  Ruvents\ReformBundle\Form\TypeExtension\FormTypeStatefulFileExtension:
    class: Ruvents\ReformBundle\Form\TypeExtension\FormTypeStatefulFileExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  Ruvents\ReformBundle\Form\TypeExtension\StatefulFileExtension:
    class: Ruvents\ReformBundle\Form\TypeExtension\StatefulFileExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
