services:
  Ruvents\ReformBundle\Form\Type\UploadType:
    class: Ruvents\ReformBundle\Form\Type\UploadType
    tags:
      - { name: form.type }

  Ruvents\ReformBundle\Form\TypeExtension\UploadFormTypeExtension:
    class: Ruvents\ReformBundle\Form\TypeExtension\UploadFormTypeExtension
    arguments:
      - "@Ruvents\\ReformBundle\\Form\\Type\\UploadType"
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
